export const praticiens = [
{
  id: 1,
  categorie: "druide",
  badge: "http://localhost:4242/assets/images/badgeDruide.png",
  nom: "Chênefort Belmir",
  age: "302 ans",
  specialite: "Grand expert en phytomagie ancestrale, infusion de cailloux énergétiques (qu’il jure efficaces), lecture de vol d’oiseaux pour prédire la météo, et alignement des moustaches de blaireau (rituel très précis, paraît-il)",
  presentation: "Druide depuis plus de 150 lunes. Parle aux plantes, prétend qu'elles répondent, et commence souvent ses consultations par 'As-tu remercié ton arbre préféré aujourd'hui ?'",
  tarif: "Consultation standard : 3 glands et 1 branche de gui (ou 40€ pour les citadins)",
  adresse: "Clairière du Vieux Chêne, troisième tronc à droite. 12 min à pied si les esprits sont de bonne humeur",
  imagePraticien: "https://i.pinimg.com/736x/f8/8f/5c/f88f5c46a3c0bee8877107934067aeaf.jpg",
  imageLieu: "https://i.pinimg.com/736x/47/98/92/479892d5c43a00bd77ea345ec4adaa13.jpg"
},
{
  id: 2,
  categorie: "voyant",
  badge: "http://localhost:4242/assets/images/badgeVoyant.png",
  nom: "Ysoria la Clairvoyante du Bois-Brume",
  age: "43 ans",
  specialite: "Voyance runique et interprétation des murmures astrals",
  description: "Maîtresse des visions étranges, Ysoria contemple les volutes d'encens jusqu’à ce que les esprits acceptent enfin de lui répondre. Elle parle souvent en devinettes, parfois même sans raison, mais ses prophéties – qu'elles soient terrifiantes ou absurdes – finissent toujours par se réaliser d’une manière ou d’une autre.",
  tarif: "3 pièces d’argent, ou une plume de griffon impeccablement propre.",
  adresse: "Marchez vers le nord jusqu’à ce que les arbres semblent vous observer, tournez à gauche au rocher qui ressemble vaguement à un hérisson géant, puis avancez jusqu'à sentir une odeur de sauge brûlée. Sa hutte apparaît lorsque vous clignez des yeux trois fois.",
  imagePraticien: "https://i.pinimg.com/736x/a1/36/8e/a1368ec5af24b2240f9362e2bb18017b.jpg",
  imageLieu: "https://i.pinimg.com/736x/83/01/ef/8301eff5fdeac85c0fd1e0e1c6ca6ff8.jpg"
},
{
  id: 17,
  categorie: "druide",
  badge: "http://localhost:4242/assets/images/badgeDruide.png",
  nom: "Feuilledor Mériwyn",
  age: "247 ans",
  specialite: "Maître des potions fumantes, guérison par chants d'écureuils, et spécialiste autoproclamée du 'massage énergétique de branches'",
  presentation: "Connue pour préparer des potions qui sentent soit très bon, soit très… surprenant. Jure que les écureuils lui transmettent des secrets médicinaux indispensables.",
  tarif: "15 feuilles de chêne ou 35€ la séance (réduction si vous apportez un chant d’oiseau enregistré)",
  adresse: "Cabane suspendue dans le Grand Hêtre Doré. Accessible par une échelle en lianes (attention aux glissades).",
  imagePraticien: "",
  imageLieu: ""
},
{
  id: 18,
  categorie: "druide",
  badge: "http://localhost:4242/assets/images/badgeDruide.png",
  nom: "Roche-Pâle Galdor",
  age: "389 ans (mais ne les fait pas, selon lui)",
  specialite: "Lithomancie (lecture de cailloux parlants), concoction de fumées divinatoires, et expertise en siestes chamaniques",
  presentation: "Galdor affirme que les pierres lui parlent. Le problème, c’est qu’il répond vraiment. Ses consultations sont courtes, mais ses siestes sont longues.",
  tarif: "Une pierre 'qui a une bonne vibration' ou 30€",
  adresse: "Grotte de la Pierre Murmurante. Suivre l'écho… ou attendre que Galdor sorte faire une sieste dehors.",
  imagePraticien: "",
  imageLieu: ""
},
{
  id: 19,
  categorie: "druide",
  badge: "http://localhost:4242/assets/images/badgeDruide.png",
  nom: "Brumefeu Althéon",
  age: "512 ans (officiellement), mais personne n’a jamais vu son acte de naissance",
  specialite: "Maîtrise du feu doux, fumigations sacrées, bénédictions des fourneaux et cuisine médicinale expérimentale",
  presentation: "Althéon fait des remèdes… comestibles. Certains ont même bon goût. Il affirme pouvoir purifier l’âme avec une bonne soupe fumée.",
  tarif: "Un pot en terre cuite ou 45€ (supplément si explosion involontaire de potion)",
  adresse: "Atelier de Fumées Sacrées, au bord du ruisseau crépitant.",
  imagePraticien: "",
  imageLieu: ""
},
{
  id: 20,
  categorie: "druide",
  badge: "http://localhost:4242/assets/images/badgeDruide.png",
  nom: "Lunargent Ysilde",
  age: "183 ans",
  specialite: "Manipulation de la rosée lunaire, harmonisation des rêves, et redirection d’énergies capricieuses",
  presentation: "Ysilde travaille surtout la nuit, affirmant que la lune lui envoie des consignes. Très douce, mais parfois en pleine conversation avec… personne.",
  tarif: "2 fioles de rosée du matin ou 38€",
  adresse: "Jardin de Lune, clairière argentée accessible uniquement à la tombée du jour.",
  imagePraticien: "",
  imageLieu: ""
},
{
  id: 21,
  categorie: "apothicaire",
  badge: "http://localhost:4242/assets/images/badgeApothicaire.png",
  nom: "Mercurole Thalian",
  age: "127 ans",
  specialite: "Préparation de sirops alchimiques, décoctions pétillantes et baumes qui 'picotent juste ce qu'il faut'",
  presentation: "Thalian prétend pouvoir transformer n'importe quelle plante en remède… parfois même en dessert. Par contre, il confond souvent ses bocaux, donc résultat variable.",
  tarif: "12€ ou un bouquet d’herbes fraîches",
  adresse: "Échoppe des Mille Fioles, au croisement du ruisseau parfumé",
  imagePraticien: "https://i.pinimg.com/1200x/0a/70/68/0a70683e9cdc29f652c7ebb56b0336f0.jpg",
  imageLieu: "https://i.pinimg.com/1200x/a4/4d/7b/a44d7bfbd2314b437f58671dab11f301.jpg"
},
{
  id: 22,
  categorie: "apothicaire",
  badge: "http://localhost:4242/assets/images/badgeApothicaire.png",
  nom: "Saugevive Elona",
  age: "203 ans",
  specialite: "Infusions calmantes, huiles parfumées, et poudres d'évasion émotionnelle (garantie sans effets secondaires… normalement)",
  presentation: "Elona murmure à ses fioles pour 'les encourager au bon comportement'. Ses remèdes sentent toujours délicieusement bon, même quand ils ne devaient pas.",
  tarif: "20€ ou un panier de fleurs sauvages",
  adresse: "Atelier Fleur-du-Vent, petite maison sous le chêne parfumé",
  imagePraticien: "https://i.pinimg.com/736x/79/3c/3e/793c3e91e776ae72ce517cd2e53c4403.jpg",
  imageLieu: "https://i.pinimg.com/1200x/52/ef/4a/52ef4a86c7eefafac956556c9de77b31.jpg"
},
{
  id: 23,
  categorie: "apothicaire",
  badge: "http://localhost:4242/assets/images/badgeApothicaire.png",
  nom: "Bourrache Firmin",
  age: "88 ans",
  specialite: "Cataplasmes express, cures de racines râpées et onguents anti-grincements articulaires",
  presentation: "Firmin note tout dans un grand carnet couvert de tâches de plantes. Il travaille vite, parle vite, et applique ses remèdes encore plus vite. Pas toujours le temps d'expliquer.",
  tarif: "8€ ou une racine 'au caractère affirmé'",
  adresse: "Comptoir de la Racine Joyeuse, près du vieux pont en mousse",
  imagePraticien: "https://i.pinimg.com/736x/46/9c/1b/469c1b85bf7bae6893e8f8a25150a89b.jpg",
  imageLieu: "https://i.pinimg.com/1200x/e2/31/a1/e231a1c34394489ccb34c68fb9be6aec.jpg"
},
{
  id: 24,
  categorie: "apothicaire",
  badge: "http://localhost:4242/assets/images/badgeApothicaire.png",
  nom: "Mélisande Ondebrise",
  age: "162 ans",
  specialite: "Tisanes d’harmonie, filtres d'énergie douce et élixirs anti-stress certifiés '100% zen'",
  presentation: "Mélisande parle lentement, très lentement… au point que certains clients atteignent déjà un état de relaxation avant même de boire quoi que ce soit.",
  tarif: "25€ ou une bougie parfumée artisanale",
  adresse: "Maison des Brumes Douces, au bord du lac argenté",
  imagePraticien: "https://i.pinimg.com/1200x/63/de/1b/63de1b1243fd45337b74071fb4b67e1b.jpg",
  imageLieu: "https://i.pinimg.com/1200x/9f/05/80/9f058032d0512943068e229c18275cab.jpg"
},
{
  id: 25,
  categorie: "apothicaire",
  badge: "http://localhost:4242/assets/images/badgeApothicaire.png",
  nom: "Grimpe-Liane Oswald",
  age: "140 ans",
  specialite: "Baumes réparateurs, lotions étonnamment collantes mais très efficaces, et essences de forêt distillées",
  presentation: "Oswald grimpe partout pour récolter ses ingrédients : arbres, toits, étagères, clients… Il ne tient pas en place, mais ses remèdes font l’unanimité.",
  tarif: "18€ ou une poignée de graines rares",
  adresse: "Laboratoire Sylvestre, cabanon accroché à un tronc gigantesque",
  imagePraticien: "https://i.pinimg.com/736x/58/b1/8e/58b18e11cf3c97f92e44078d250560b4.jpg",
  imageLieu: "https://i.pinimg.com/1200x/9a/94/7d/9a947d91828cf4fb039b639e10a9869f.jpg"
},
{
  id: 26,
  categorie: "devin",
  badge: "http://localhost:4242/assets/images/badgeDevin.png",
  nom: "Oculus Varendir",
  age: "411 ans",
  specialite: "Lecture des ombres, interprétation des bruits de vent et prédictions basées sur le nombre de fois où un caillou trébuche",
  presentation: "Varendir voit l’avenir… ou du moins prétend le voir, surtout quand il a ses lunettes en écaille de sanglier mystique. Très sérieux, mais se trompe parfois de futur.",
  tarif: "40€ ou une plume d'oiseau 'au destin puissant'",
  adresse: "Tour de l’Ombre-Tournée, au sommet d’un rocher qui n’existait pas la veille",
  imagePraticien: "https://i.pinimg.com/1200x/a4/12/77/a41277b2142222b478ce5d088a7f4d0e.jpg",
  imageLieu: "https://i.pinimg.com/736x/c1/bd/3f/c1bd3f743232977a3d9914b4c8368585.jpg"
},
{
  id: 27,
  categorie: "devin",
  badge: "http://localhost:4242/assets/images/badgeDevin.png",
  nom: "Lunéra Sélénys",
  age: "278 ans",
  specialite: "Visions lunaires, tirage d’orbes argentées, et interprétation des rêves félins",
  presentation: "Sélénys ne prédit que la nuit, persuadée que le soleil 'parasite les vérités'. Toujours accompagnée d’un chat qui regarde fixement les gens—assez déstabilisant.",
  tarif: "33€ ou une fiole de lumière de lune (factice acceptée)",
  adresse: "Sanctuaire de la Lune Blanche, seulement visible après le crépuscule",
  imagePraticien: "https://i.pinimg.com/736x/83/b7/c0/83b7c0245ef73844aac4db49c174a811.jpg",
  imageLieu: "https://i.pinimg.com/736x/ab/8d/3e/ab8d3e12a1cf83b80e5ffc8b6077c99f.jpg"
},
{
  id: 28,
  categorie: "devin",
  badge: "http://localhost:4242/assets/images/badgeDevin.png",
  nom: "Tarcis Brouillâme",
  age: "350 ans",
  specialite: "Prédiction par fumées sacrées, vision dans la brume, et prophéties… un peu vagues",
  presentation: "Tarcis est très précis… mais jamais sur la bonne personne. Ses visions sont souvent exactes, mais concernent quelqu’un d’autre. Très fumant mais attachant.",
  tarif: "22€ ou un encens rare",
  adresse: "Caverne des Brumes Égarées, toujours entourée d’un léger brouillard",
  imagePraticien: "https://i.pinimg.com/1200x/f9/6f/3d/f96f3d36fefdca9d3ded6aa1f432fb13.jpg",
  imageLieu: "https://i.pinimg.com/736x/96/76/b3/9676b3f2f3225df6eaf7fbb291b8d4f6.jpg"
},
{
  id: 29,
  categorie: "devin",
  badge: "http://localhost:4242/assets/images/badgeDevin.png",
  nom: "Éclairâme Vellior",
  age: "192 ans",
  specialite: "Cartomancie ancienne, lecture des fissures dans la pierre, et oracles improvisés selon l’humeur du ciel",
  presentation: "Vellior adore faire du suspense. Il retourne les cartes en très slow motion, juste pour dramatiser. Ses prédictions sont frappantes, parfois même littéralement.",
  tarif: "28€ ou un caillou fendu 'du destin'",
  adresse: "Terrasse des Oracles, plateau rocheux face au lever du soleil",
  imagePraticien: "https://i.pinimg.com/736x/a3/0b/f1/a30bf1691813b5e4eeb890b690518841.jpg",
  imageLieu: "https://i.pinimg.com/736x/32/f1/22/32f1226988793564cb907602a9948d98.jpg"
},
{
  id: 30,
  categorie: "devin",
  badge: "http://localhost:4242/assets/images/badgeDevin.png",
  nom: "Mirevoix Althéna",
  age: "230 ans",
  specialite: "Prédiction par murmures, écoute des 'voix du destin', et interprétation des soupirs humains (très pointu)",
  presentation: "Althéna entend tout : les secrets, les doutes, même le bruit que fait votre destin quand il change de direction. Parle doucement, écoute fort.",
  tarif: "30€ ou un secret bien gardé",
  adresse: "Cabane des Murmures, au cœur d’un cercle de pierres anciennes",
  imagePraticien: "https://i.pinimg.com/736x/0b/b6/6e/0bb66e033f5953c008352f1a23f1c0bc.jpg",
  imageLieu: "https://i.pinimg.com/736x/75/67/64/756764ce8b140b38e004eda4025e1776.jpg"
}
];
